export {default as Calendar} from './Calendar';
export {default as Customers} from './Customers';
export {default as Ecommerce} from './Ecommerce';
export {default as Editor} from './Editor';
export {default as Employees} from './Employees';
export {default as Kanban} from './Kanban';
export {default as Orders} from './Orders';
export {default as Line} from './Charts/Line';
export {default as Pie} from './Charts/Pie';
